version: '3'
services:
  # WHISK INVOKER AGENT
  invoker:
    image: ${DOCKER_IMAGE_PREFIX:-openwhisk}/invoker
    command: /bin/sh -c "exec /init.sh --id 0 >> /logs/invoker-local_logs.log 2>&1"
    privileged: true
    pid: "host"
    userns_mode: "host"
    # links:
    #   - db:db.docker
    #   - kafka:kafka.docker
    #   - zookeeper:zookeeper.docker
    # depends_on:
    #   - db
    #   - kafka
    env_file:
      - ./docker-whisk-controller.env # env vars shared
      - ~/tmp/openwhisk/local.env     # generated during make setup
    environment:
      COMPONENT_NAME: invoker
      SERVICE_NAME: invoker0
      PORT: 8085

      KAFKA_HOSTS: ${DOCKER_COMPOSE_HOST}:9092
      ZOOKEEPER_HOSTS: ${DOCKER_COMPOSE_HOST}:2181

      CONFIG_whisk_couchdb_provider: CouchDB
      CONFIG_whisk_couchdb_protocol: http
      CONFIG_whisk_couchdb_port: 5984
      CONFIG_whisk_couchdb_host: ${DOCKER_COMPOSE_HOST}
      CONFIG_whisk_couchdb_username: whisk_admin
      CONFIG_whisk_couchdb_password: some_passw0rd

      EDGE_HOST: ${DOCKER_COMPOSE_HOST}
      EDGE_HOST_APIPORT: 443

      CONFIG_whisk_containerFactory_containerArgs_network: openwhisk_default

      WHISK_API_HOST_NAME: ${DOCKER_COMPOSE_HOST}
    volumes:
      - ~/tmp/openwhisk/invoker/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/containers
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - "8085:8085"
      - "9333:9222"
